export const TestCase = {
	parsesInlineZodNumber: 'parses-inline-zod-number',
	parsesInlineZodString: 'parses-inline-zod-string',
	parsesInlineZodObject: 'parses-inline-zod-object',
	parsesInlineZodNumberArray: 'parses-inline-zod-number-array',
	parsesInlineZodObjectArray: 'parses-inline-zod-object-array',
	parsedAliasedZodSchema: 'parses-aliased-zod-schema',
	parsesReturnRecordStringUnknown: 'parses-return-record-string-unknown',
	parsesReturnObjectWithRecordProperty: 'parses-return-object-with-record-property',
	parsesBufferReturnedFromFunction: 'parses-buffer-returned-from-function',
	parsesDateReturnedFromFunction: 'parses-date-returned-from-function',
	parsesMapReturnedFromFunction: 'parses-map-returned-from-function',
	parsesSetReturnedFromFunction: 'parses-set-returned-from-function',
	parsesRegExpReturnedFromFunction: 'parses-regexp-returned-from-function',
	parsesErrorReturnedFromFunction: 'parses-error-returned-from-function',
	parsesInt8ArrayReturnedFromFunction: 'parses-int8array-returned-from-function',
	parsesFloat32ArrayReturnedFromFunction: 'parses-float32array-returned-from-function',
	parsesArrayBufferReturnedFromFunction: 'parses-arraybuffer-returned-from-function',
	parsesReadableStreamReturnedFromFunction: 'parses-readablestream-returned-from-function',
	parsesPrismaJsonObjectReturnedFromFunction: 'parses-prisma-jsonobject-returned-from-function',
} as const
